Cy-Weather : Main.o tabSort.o sortM.o sortH.o sortW.o sortP1.o sortT1.o sortT2.o sortP2.o
	gcc -o ../../Cy-Weather Main.o tabSort.o sortM.o sortH.o sortW.o sortP1.o sortT1.o sortT2.o sortP2.o

Main.o : Main.c
	gcc -o Main.o -c Main.c

tabSort.o : ./Sort/tabSort.c
	gcc -o tabSort.o -c ./Sort/tabSort.c

sortM.o : ./Type/sortM.c
	gcc -o sortM.o -c ./Type/sortM.c

sortH.o : ./Type/sortH.c
	gcc -o sortH.o -c ./Type/sortH.c

sortW.o : ./Type/sortW.c
	gcc -o sortW.o -c ./Type/sortW.c

sortP1.o : ./Type/sortP1.c
	gcc -o sortP1.o -c ./Type/sortP1.c

sortT1.o : ./Type/sortT1.c
	gcc -o sortT1.o -c ./Type/sortT1.c
	
sortT2.o : ./Type/sortT2.c
	gcc -o sortT2.o -c ./Type/sortT2.c

sortP2.o : ./Type/sortP2.c
	gcc -o sortP2.o -c ./Type/sortP2.c